# Generated by Django 5.1.1 on 2024-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForjaApp', '0005_genre_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
